require("yaml")
cnf = YAML::load(File.open('manifest.yml'))

instances = cnf['instances']
box = cnf['box']
provider = cnf['provider']
name_prefix = cnf['name_prefix']
name_suffix = cnf['name_suffix']
ip_prefix = cnf['ip_prefix']
memory = cnf['memory']
cpus = cnf['cpus']
path = cnf['path']

Vagrant.configure("2") do |config|
  instances.times do |i|
    node_id = "#{name_prefix}#{i}"
    config.vm.define node_id do |node|
      node.vm.box = "#{box}"
      node.vm.hostname = "#{name_prefix}#{i}#{name_suffix}"
      node.vm.network "private_network", ip: "#{ip_prefix}#{i}"
      node.vm.provider "#{provider}" do |vm|
        vm.memory = "#{memory}"
        vm.cpus = "#{cpus}"
      end
      node.vm.provision "shell", path: "#{path}"
    end
  end
end
